set(QTC_DEBUG_MODE OFF
    CACHE BOOL "Debug mode for print more infomation"
)

macro(trace target)
    message(STATUS "[${target}] ${ARGN}")
endmacro()

macro(trace_global_flags target)
    foreach(var
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_RELEASE
        CMAKE_C_FLAGS_MINSIZEREL
        CMAKE_C_FLAGS_RELWITHDEBINFO
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL
        CMAKE_CXX_FLAGS_RELWITHDEBINFO
        CMAKE_C_CREATE_SHARED_LIBRARY
        CMAKE_C_CREATE_SHARED_MODULE
        CMAKE_C_CREATE_STATIC_LIBRARY
        CMAKE_C_COMPILE_OBJECT
        CMAKE_C_LINK_EXECUTABLE
        CMAKE_CXX_CREATE_SHARED_LIBRARY
        CMAKE_CXX_CREATE_SHARED_MODULE
        CMAKE_CXX_CREATE_STATIC_LIBRARY
        CMAKE_CXX_COMPILE_OBJECT
        CMAKE_CXX_LINK_EXECUTABLE
        CMAKE_EXE_LINKER_FLAGS
        CMAKE_EXE_LINKER_FLAGS_DEBUG
        CMAKE_EXE_LINKER_FLAGS_RELEASE
        CMAKE_EXE_LINKER_FLAGS_MINSIZEREL
        CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO
        CMAKE_SHARED_LINKER_FLAGS
        CMAKE_LINK_LIBRARY_FILE_FLAG
        CMAKE_LINK_LIBRARY_FLAG
        )
        trace(${target} "${var} = ${${var}}")
    endforeach()
endmacro()
